### ISSUE TITLE
TypeError @ _setup_cookie when signing/logging in

### ISSUE THREAD

**Issue by nyiyui** [FedericoCeratto/bottle-cork#122]
Cork v0.12
Bottle v0.13-dev
[Source (ZIP File)](https://github.com/FedericoCeratto/bottle-cork/files/3267207/Source.zip)

Python 3 Output
```
Bottle v0.13-dev server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

172.18.0.1 - - [07/Jun/2019 18:34:40] "GET / HTTP/1.1" 200 1076
172.18.0.1 - - [07/Jun/2019 18:34:40] "GET /rsc/css/index HTTP/1.1" 404 764
172.18.0.1 - - [07/Jun/2019 18:34:40] "GET /rsc/js/acnt/signin HTTP/1.1" 404 774
172.18.0.1 - - [07/Jun/2019 18:34:40] "GET /rsc/js/index HTTP/1.1" 404 762
172.18.0.1 - - [07/Jun/2019 18:34:40] "GET /rsc/img/favicon HTTP/1.1" 200 0
172.18.0.1 - - [07/Jun/2019 18:34:40] "GET /rsc/js/acnt/signin HTTP/1.1" 404 774
kenxshibata kenxshibata <- this is debug output for username and password I know it's a security hole
Traceback (most recent call last):
  File "/home/runner/bottle.py", line 996, in _handle
    out = route.call(**args)
  File "/home/runner/bottle.py", line 2007, in wrapper
    rv = callback(*a, **ka)
  File "main.py", line 21, in login
    auth.login(username, password, success_redirect='/acnt/signin/success', fail_redirect='/acnt/signin/fail')
  File "/home/runner/cork/cork/cork.py", line 130, in login
    self._setup_cookie(username)
  File "/home/runner/cork/cork/cork.py", line 603, in _setup_cookie
    session['username'] = username
TypeError: 'NoneType' object does not support item assignment
172.18.0.1 - - [07/Jun/2019 18:34:41] "POST /acnt/signin HTTP/1.1" 500 770```

**Comment by cadaverous-lives** [comment]
I'm getting this same error:

Traceback (most recent call last):
  File "/home/cadaverous/.local/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/cadaverous/.local/lib/python3.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "/home/cadaverous/Projects/webapptut/todo.py", line 24, in do_login
    auth.login(username, password, "/home", "/login/retry")
  File "/home/cadaverous/.local/lib/python3.7/site-packages/cork/cork.py", line 130, in login
    self._setup_cookie(username)
  File "/home/cadaverous/.local/lib/python3.7/site-packages/cork/cork.py", line 603, in _setup_cookie
    session['username'] = username
TypeError: 'NoneType' object does not support item assignment``
