### ISSUE TITLE
simple_webapp_using_mongodb.py: TypeError("__init__() got an unexpected keyword argument 'fields'",)

### ISSUE THREAD

**Issue by bobeina** [FedericoCeratto/bottle-cork#91]
I got this error when I accessed /admin page.
Solution first:
In method __iter() of class MongoTable, mongodb_backend.py:
Replace line 53
r = self._coll.find(fields=[self.key_name,])
with
r = self._coll.find( { self.key_name : { '$exists': True } } )
-------------------------------
Here is traceback:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib64/python2.7/site-packages/bottle.py", line 3615, in wrapper
    result = func(*args, **kwargs)
  File "blog.py", line 169, in admin
    for i in tu:
  File "/usr/lib64/python2.7/site-packages/cork/cork.py", line 314, in list_users
    for un in sorted(self._store.users):
  File "/usr/lib64/python2.7/site-packages/cork/mongodb_backend.py", line 53, in __iter__
    r = self._coll.find(fields=[self._key_name,])    #debug
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 929, in find
    return Cursor(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fields'

**Comment by helgisteinar** [comment]
Think 
        r = self._coll.find( { self._key_name : { '$exists': True } } )

that is _key_name vs. key_name
